version: 0.2

phases:
  build:
    commands:
    - newman run STest.postman_collection.json -e STest.postman_environment.json -d ListofAuthor.json -n 4 -r cli,junit --reporter-html-export report1.html --insecure
    - newman run SNegTest.postman_collection.json -e STestNeg.postman_environment.json -d badUserpwd.json -n 5 -r cli,junit --reporter-html-export report2.html --insecure
artifacts:
  files:
    - '**/*'
